### PR TITLE
miscellaneous fixes

### PR DESCRIPTION
**Pull request by hramrach**
I don't know how to set the icon path to the location where the icon is installed.

Is there some definition that qmake provides for it?

If not maybe it should be included ass resource.

### CODE REVIEW

**Comment by dependon** [comment]
I think I just wrote about the icon without paying special attention.    I have a question: How to exit and call out if the tray is deleted

**Comment by dependon** [comment]
I want to provide a macro to control whether there is a tray

**Comment by hramrach** [comment]
There is no way to exit without the tray icon other than killing the binary such as

`killall x11-transparency-tools`

It is fine to provide a commandline option to hide the tray. Hiding it from the tray menu with no way to get it back is not great user experience.

**Comment by dependon** [comment]
You can make a command line tool that only changes the transparency of the current window, which is also good

**Pull request merged**
